code:
  - changed-files:
      - any-glob-to-any-file:
          - src/**

tests:
  - changed-files:
      - any-glob-to-any-file:
          - tests/**

spec:
  - changed-files:
      - any-glob-to-any-file:
          - openspec/**

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
